# Generated by Django 5.1.6 on 2025-03-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('student_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_1', to='students.student')),
                ('student_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_2', to='students.student')),
            ],
        ),
    ]
