# Generated by Django 5.1.6 on 2025-03-09 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_matchresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='match_score',
            new_name='match_probability',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='student_1',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='student_2',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='student_id_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='student_id_2',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_score', models.FloatField(default=0.0, help_text='Match effectiveness rating (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_initiated', to=settings.AUTH_USER_MODEL)),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student_a', 'student_b')},
            },
        ),
    ]
