# Generated by Django 5.1.6 on 2025-03-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_voicemessage'),
    ]

    operations = [
    ]
