# Generated by Django 5.1.6 on 2025-03-16 10:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20250316_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='semesters',
                to='students.Student'  # This forces the FK to reference the Student model
            ),
        ),
    ]
